version: '2'

services:
  postgres:
    build: ./postgres
    volumes:
      - ./mnt/postgres_data:/var/lib/postgresql/data
      - ./mnt/postgres_backup:/backups
    env_file: .env
    restart: unless-stopped

  teamcity-server:
    build: ./teamcity_server
    volumes:
      - ./mnt/teamcity_server_data:/data/teamcity_server/datadir
      - ./mnt/teamcity_server_logs:/opt/teamcity/logs
    ports:
      - 8111:8111
    depends_on:
      - postgres
    env_file: .env
    restart: unless-stopped

  teamcity-agent:
    build: ./teamcity_agent
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./mnt/rvm:/usr/local/rvm
